services:
  app:
    build:
      context: .
      args:
        MIRROR_CN: "true"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    environment:
      - SQLITE_DB_PATH=/var/www/html/database/app.db
    restart: unless-stopped

volumes:
  vendor_data:
